[package]
name = "get-account-nft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpl-token-metadata = "1.3.3"
solana-program = "1.11.4"
solana-sdk = "1.11.5"