[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
escrow = "GShJcD9o7ZSPzMvCkbNbt1cUaHSuCWfsfDP1qVvWhHTH"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/*.ts"
